controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

contact:
    path:       /{_locale}/contact
    controller: App\Controller\HomeController::changeLanguage
    requirements:
        _locale: en|fr